FROM

LABEL MAINTAINER="Branson Fox <bransonf@wustl.edu>"

# Notes
# Need Caddy for TLS Reverse Proxy...
# ... To a Gunicorn WSGI ...
# ... To a Bundled Flask API ...
# ... Requiring Both Python and R ...
# ... as well as psycopg2 sys dependencies.
#

